### PR TITLE
Python 2.7 & Reproducible Randomness

### PR DESCRIPTION
**Pull request by tgsmith61591**
Lots of changes, not the least of which is Python 2.7 compatibility and tests. More specifically:

- Added random_seed to config JSON as referenced in #6  
- Methods with random choices generate from the random_state (#6)
- Added utils module for type checking
- Added defaults for config values
- Removed duplicate code where possible
- Removed unittest framework in favor of nosetests

Furthermore, there are scattered TODOs that need addressing. One for @mbernico and several for @scollins83

### CODE REVIEW

**Comment by tgsmith61591** [comment]
We lost just a bit of coverage, but it's from lines added. We didn't lose any previously covered lines...

**Review by mbernico — APPROVED** [review]
+1   There is a ton of really good stuff here.  Thank you Taylor

**Comment by scollins83** [comment]
@tgsmith61591 : In regard to this:
Furthermore, there are scattered TODOs that need addressing. One for mbernico and several for scollins83

Maybe I missed something in the merge, but are these listed anywhere? I had planned to refactor both my tests and my code at some point anyway, so I can fold these items in.

**Comment by tgsmith61591** [comment]
I should have included them in the PR.. sorry about that. They're in
make_dataset.

**Comment by scollins83** [comment]
NP--- I thought I'd synced my fork back up with the original, but I hadn't. NOW I see them!
I'll go back through in the next few days and adjust some of my MVP hackiness :-)

**Pull request merged**
